/*
This assignment is about working with the Spotify API for developers.
The goal is to create a simple web application that allows users to search for artists and get information about them.
*/

// Define the variables that we will use in the code
let selecList = document.getElementById('artists');
let accessToken = '';
const clientId = '72fe3696461e4ed9ae6446576f34f8d8';
const clientSecret = '96ec0d1017024a3bbad077176b284cab';
// since the API needs a artist ID, we need to get it from the search results
let artists = {
    "Pitbull": "0TnOYISbd1XYRBk9myaseg",
    "Rihanna": "5pKCCKE2ajJHZ9KAiaK11H",
    "Beyoncé": "6vWDO969PvNqNYHIOW5v0m",
    "Adele": "4dpARuHxo51G3z768sgnrY",
    "Justin Bieber": "1uNFoZAHBGtllmzznpCI3s",
    "Shakira": "0EmeFodog0BfCgMzAIvKQp",
    "Michael Jackson": "3fMbdgg4jU18AjLCKBhRSm",
    "Madonna": "6tbjWDEIzxoDsBA1FuhfPW",
    "Taylor Swift": "06HL4z0CvFAxyc27GXpf02",
    "Lady Gaga": "1HY2Jd0NmPuamShAr6KMms",
    "Ariana Grande": "66CXWjxzNUsdJxJ2JdwvnR",
    "Katy Perry": "6jJ0s89eD6GaHleKKya26X",
    "Ed Sheeran": "6eUKZXaKkcviH0Ku9w2n3V",
    "Drake": "3TVXtAsR1Inumwj472S9r4",
    "Bruno Mars": "0du5cEVh5yTK9QJze8zA0C",
    "The Weeknd": "1Xyo4u8uXC1ZmMpatF05PJ",
}

// First populate the select list with the artists
for (let artist in artists) {
    let option = document.createElement('option');
    option.value = artist;
    option.text = artist;
    selecList.appendChild(option);
}

// Then we need to get the access token from the Spotify API


/* This piece of code was generated by Postman */
const myHeaders = new Headers();
myHeaders.append("Content-Type", "application/x-www-form-urlencoded");
myHeaders.append("Cookie", "__Host-device_id=AQB6LSJxwHc3aHOK9llwPEA34Qlu9xeIgtQoxUXAND8oCFAow5kSWFjylxYVcNfJMZLrQm0IqcQoetvrimQ73pvLV4h-iJboZvI; sp_tr=false");

const urlencoded = new URLSearchParams();
urlencoded.append("grant_type", "client_credentials");
urlencoded.append("client_id", clientId);
urlencoded.append("client_secret", clientSecret);

const requestOptions = {
    method: "POST",
    headers: myHeaders,
    body: urlencoded,
    redirect: "follow"
};


fetch("https://accounts.spotify.com/api/token", requestOptions)
    .then((response) => response.json())
    .then((result) => {
        // here we have the access token, and we can use it to make requests to the Spotify API
        console.log(result)
        accessToken = result.access_token;
        console.log(accessToken)
    })
    .catch((error) => console.error(error));


// Now we can start working with the Spotify API
function callTheSpotifyAPI(artistId) {
    const headers = new Headers();
    headers.append("Authorization", `Bearer ${accessToken}`);

    const requestOptions = {
    method: "GET",
    headers: headers,
    redirect: "follow"
    };

    fetch("https://api.spotify.com/v1/artists/"+artistId, requestOptions)
    .then((response) => response.json())
    .then((result) => {
        console.log(result)
        return result;
    })
    .catch((error) => console.error(error));
}

// First we need to create a function that will search for artists
function searchArtist() {
    // Get the artist that the user has selected
    const artist = selecList.value;
    // Defining the artist ID
    const artistId = artists[artist];
    // Define the headers for the API request
    callTheSpotifyAPI(artistId);
}

// Add an event listener to the select list
selecList.addEventListener('change', searchArtist);