/*
This assignment is about working with the Spotify API for developers.
The goal is to create a simple web application that allows users to search for artists and get information about them.
*/

// Define the variables that we will use in the code
const searchButton = document.getElementById('search-button');
const searchInput = document.getElementById('search');
// since the API needs a artist ID, we need to get it from the search results
let apiVariables =
    { 
        "searchTerm": "placeholder", 
        "offset": 0, 
        "limit": 10, 
        "numberOfTopResults": 5, 
        "includeAudiobooks": true, 
        "includeArtistHasConcertsField": false, 
        "includePreReleases": true, 
        "includeLocalConcertsField": false 
    }
let extensions =
    {
        "persistedQuery":{
            "version":1,
            "sha256Hash":"f1f1c151cd392433ef4d2683a10deb9adeefd660f29692d8539ce450d2dfdb96"
        }
    } 
// First we need to get the access token from the Spotify API
let accessToken = '';
const clientId = '72fe3696461e4ed9ae6446576f34f8d8';
const clientSecret = '96ec0d1017024a3bbad077176b284cab';

/* This piece of code was generated by Postman */
const myHeaders = new Headers();
myHeaders.append("Content-Type", "application/x-www-form-urlencoded");
myHeaders.append("Cookie", "__Host-device_id=AQB6LSJxwHc3aHOK9llwPEA34Qlu9xeIgtQoxUXAND8oCFAow5kSWFjylxYVcNfJMZLrQm0IqcQoetvrimQ73pvLV4h-iJboZvI; sp_tr=false");

const urlencoded = new URLSearchParams();
urlencoded.append("grant_type", "client_credentials");
urlencoded.append("client_id", clientId);
urlencoded.append("client_secret", clientSecret);

const requestOptions = {
    method: "POST",
    headers: myHeaders,
    body: urlencoded,
    redirect: "follow"
};

fetch("https://accounts.spotify.com/api/token", requestOptions)
    .then((response) => response.json())
    .then((result) => {
        // here we have the access token, and we can use it to make requests to the Spotify API
        console.log(result)
        accessToken = result.access_token;
        console.log(accessToken)
    })
    .catch((error) => console.error(error));

// 


// Now we can start working with the Spotify API
// First we need to create a function that will search for artists
function searchArtist() {
    // Get the value from the input field
    const artist = document.getElementById('search').value;
    // Make the request to the Spotify API
    fetch(`https://api.spotify.com/v1/search?q=${artist}&type=artist`, {
        headers: {
            'Authorization': `Bearer ${accessToken}`
        }
    })
        .then((response) => response.json())
        .then((data) => {
            // Get the artist from the data
            const artist = data.artists.items[0];
            // Create the HTML that will be displayed on the page
            const html = `
        <div>
          <img src="${artist.images[0].url}" alt="${artist.name}">
          <h2>${artist.name}</h2>
          <p>${artist.followers.total} followers</p>
          <p>${artist.genres.join(', ')}</p>
          <p>${artist.popularity} popularity</p>
        </div>
      `;
            // Display the HTML on the page
            document.getElementById('result').innerHTML = html;
        })
        .catch((error) => console.error(error));
}

