/*
This assignment is about working with the Spotify API for developers.
The goal is to create a simple web application that allows users to search for artists and get information about them.
*/

// Define the variables that we will use in the code
const searchButton = document.getElementById('search-button');
const searchInput = document.getElementById('search');
// since the API needs a artist ID, we need to get it from the search results

// First we need to get the access token from the Spotify API
let accessToken = '';
const clientId = '72fe3696461e4ed9ae6446576f34f8d8';
const clientSecret = '96ec0d1017024a3bbad077176b284cab';

/* This piece of code was generated by Postman */
const myHeaders = new Headers();
myHeaders.append("Content-Type", "application/x-www-form-urlencoded");
myHeaders.append("Cookie", "__Host-device_id=AQB6LSJxwHc3aHOK9llwPEA34Qlu9xeIgtQoxUXAND8oCFAow5kSWFjylxYVcNfJMZLrQm0IqcQoetvrimQ73pvLV4h-iJboZvI; sp_tr=false");

const urlencoded = new URLSearchParams();
urlencoded.append("grant_type", "client_credentials");
urlencoded.append("client_id", clientId);
urlencoded.append("client_secret", clientSecret);

const requestOptions = {
    method: "POST",
    headers: myHeaders,
    body: urlencoded,
    redirect: "follow"
};


// fetch("https://accounts.spotify.com/api/token", requestOptions)
//     .then((response) => response.json())
//     .then((result) => {
//         // here we have the access token, and we can use it to make requests to the Spotify API
//         console.log(result)
//         accessToken = result.access_token;
//         console.log(accessToken)
//     })
//     .catch((error) => console.error(error));

// 


// Now we can start working with the Spotify API
// First we need to create a function that will search for artists
function searchArtist() {
    // Get the value from the input field
    const artist = document.getElementById('search').value;
    // Make the request to the Spotify API
    fetch(`https://api.spotify.com/v1/search?q=${artist}&type=artist`, {
        headers: {
            'Authorization': `Bearer ${accessToken}`
        }
    })
        .then((response) => response.json())
        .then((data) => {
            // Get the artist from the data
            const artist = data.artists.items[0];
            // Create the HTML that will be displayed on the page
            const html = `
        <div>
          <img src="${artist.images[0].url}" alt="${artist.name}">
          <h2>${artist.name}</h2>
          <p>${artist.followers.total} followers</p>
          <p>${artist.genres.join(', ')}</p>
          <p>${artist.popularity} popularity</p>
        </div>
      `;
            // Display the HTML on the page
            document.getElementById('result').innerHTML = html;
        })
        .catch((error) => console.error(error));
}

function getArtistId(artist){
    apiVariables.searchTerm = artist;
    let searcVariables = URLSearchParams(apiVariables).toString();
    let searchExtension = URLSearchParams(extensions).toString();
    const myHeaders = new Headers();
    myHeaders.append("accept", "application/json");
    myHeaders.append("authorization", "Bearer BQAMZzMzXCbbjSnNUNZKcggYoLqU5AnsRqF7mNhiwQC7vgsuH8Q-RYuwftOIsXIFvzv0xpEDw0Px8hllLIuXOqUGxNPy0Fi2QeRjbzFVX-bUGPUwFtJHQSslx2BcA8eCQDA_Cg__fL3C8tMhV9yVjxdwK7LqXYn43p4Ln2-9Tpt6SxO0V_sPS5wZ00pKIajp-0Wd3q5oRcovyphOvmLcDx6bigJoZodDuclfVdI6_q5jvbzUcj7PdNncbOOOej-P8plvJb_8KncvCom3HxwfkJO4k8G392tmCR0RCjxISZYLyEWw6AdAd55Ld8ihrWVH3lYCchZDbZn5BQQoxhZNn9y6gQ_A-w");
    myHeaders.append("client-token", "AADHS77yZ+w1xC/TKgsrhXUSAzopgVePmuEI/VKvXO1uK8JgMaNBmxRzSz542yW9wQBOx/SJCg/Ff6fIxvUDOC7oJXf1vG6qJ4Y+sJCf3X80TCaUH9PbGiqPgpT731G0OCan6UCiIMbHMWsUuKWKGrQG76gMVJ6xcfkKUcmGR4rpv4vkHaPJA+oFTjim/4MW0A7Z3IsT0/6+wnBcvtX7/4JY24y5fCxEqJlNh1bVfMR8LZR2UW59uWRPxhUS3vOSGMn2v5AHjI1oZV5lnaR5Dzkz2ADNNuhNRnAZywaROg==");
    const requestOptions = {
        method: "GET",
        headers: myHeaders,
        redirect: "follow"
      };
      
      fetch(`https://api-partner.spotify.com/pathfinder/v1/query?operationName=searchDesktop&variables=${searcVariables}&extensions=${searchExtension}`, requestOptions)
        .then((response) => response.text())
        .then((result) => console.log(result))
        .catch((error) => console.error(error));
}